### PR TITLE
Use ->getResult()->getResultData() to fix deprecations in MW 1.25+

### LINKED ISSUE #76: Deprecations from MW 1.25 are causing trouble on Special:SemanticWatchlist
image

When running under E_STRICT, deprecation notices can obscure the useful information on the page.

### PR DESCRIPTION
**Pull request by hexmode**
Fixes #76

### CODE REVIEW

File: specials/SpecialSemanticWatchlist.php [hunk 1]
```diff
@@ -299,7 +299,11 @@ protected function getChangeSetsData( $limit, $continue ) {
 
 		$api = new ApiMain( new FauxRequest( $requestData, true ), true );
 		$api->execute();
-		return $api->getResultData();
+		return $api->getResult()->getResultData( null, [
```
Comment (mwjames) [inline specials/SpecialSemanticWatchlist.php]: The SWL requirements still say "MediaWiki 1.19 - 1.27", so making the code work with 1.19 using `if ... then ...` should be the objective here since I don't have time to make SWL 1.27+ only.

Comment (JeroenDeDauw) [reply specials/SpecialSemanticWatchlist.php]: Release notes state that master is already 1.22+: https://github.com/SemanticMediaWiki/SemanticWatchlist/blob/master/RELEASE-NOTES.md

Comment (JeroenDeDauw) [reply specials/SpecialSemanticWatchlist.php]: Does this PR break compat with 1.22? If so, I suggest we just raise the min required MW version.

Comment (mwjames) [reply specials/SpecialSemanticWatchlist.php]: If you have time, please do so I'm a bit busy with other things and cannot cover each and every extension!

Comment (JeroenDeDauw) [reply specials/SpecialSemanticWatchlist.php]: This does not really take time - it is the cheapest option. Retaining compat is extra work, which is why I suggest we drop it here, esp if it is about ancient MW versions anyway.

Comment (kghbln) [reply specials/SpecialSemanticWatchlist.php]: We, better I, already broke compat with MW 1.22 and lower with https://github.com/SemanticMediaWiki/SemanticWatchlist/commit/3bc15e9e39627b53dd863ccec04e148c8669c0ae 13 months ago. Probably the docu was not updated accordingly. Shame on me. :(

Comment (JeroenDeDauw) [reply specials/SpecialSemanticWatchlist.php]: README should reflect the latest release, not master, so it was fluff
